services:
  - type: web
    name: parcelpulse-api
    env: docker
    rootDir: backend
    envVars:
      - key: DB_URL
        fromDatabase:
          name: parcelpulse-db
          property: connectionString
      - key: DB_USER
        fromDatabase:
          name: parcelpulse-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: parcelpulse-db
          property: password
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
